name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    environment: default
    name: default
    container: python:3.9
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: pip install
      run: pip install -r requirements.txt
    - name: Fetch latest data
      run: python main.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
